// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {
            "name": "MIT License",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/internal/frame/{resource}/{frame_index}": {
            "get": {
                "summary": "Get frames for a particular resource",
                "parameters": [
                    {
                        "type": "string",
                        "description": "resource ID",
                        "name": "resource",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "relative frame index",
                        "name": "frame_index",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "JPEG frame",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/internal/peers/": {
            "get": {
                "summary": "Get all currently connected peers",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http.PeerList"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "http.PeerList": {
            "type": "object",
            "properties": {
                "peers": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/internal/",
	Schemes:          []string{},
	Title:            "AIEcho Ingestion Backend",
	Description:      "This backend exposes an API for ingesting video streams and providing them to internal processing APIs.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
