# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.default_api import DefaultApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_internal_frame_resource_frame_index_get(self):
        """Test case for internal_frame_resource_frame_index_get

        Get frames for a particular resource  # noqa: E501
        """
        pass

    def test_internal_peers_get(self):
        """Test case for internal_peers_get

        Get all currently connected peers  # noqa: E501
        """
        pass

    def test_internal_transcripts_resource_post(self):
        """Test case for internal_transcripts_resource_post

        Forward transcribed frame contents to client  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
